# Generated by Django 3.1.4 on 2021-01-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_Name',
            new_name='contract_name',
        ),
    ]
