# Generated by Django 3.1.4 on 2021-01-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='po',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pr',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
