# Generated by Django 3.1.4 on 2021-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20210102_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_level',
        ),
        migrations.AlterField(
            model_name='route',
            name='price_E',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='route',
            name='price_W',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19),
        ),
    ]
