# Generated by Django 3.1.4 on 2021-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20210102_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
