# Generated by Django 3.1.4 on 2021-01-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20210102_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('0', 'เบิกจ้าง'), ('1', 'จัดทำ TOR/ราคากลาง'), ('2', 'รองบประมาณ'), ('3', 'ประกวดราคา'), ('4', 'อื่นๆ')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='contracts.status'),
        ),
    ]
