# Generated by Django 3.1.4 on 2021-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20210102_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.AddField(
            model_name='contract',
            name='status_name',
            field=models.CharField(choices=[('0', 'เบิกจ้าง'), ('1', 'จัดทำ TOR/ราคากลาง'), ('2', 'รองบประมาณ'), ('3', 'ประกวดราคา'), ('4', 'อื่นๆ')], default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
