# Generated by Django 3.1.4 on 2021-01-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อสัญญา')),
                ('address', models.CharField(default='', max_length=200, verbose_name='สถานที่')),
                ('pr', models.CharField(blank=True, max_length=10)),
                ('po', models.CharField(blank=True, max_length=10)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('po_date', models.DateTimeField(blank=True, verbose_name='PO date')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='PO start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='PO end date')),
                ('status_name', models.CharField(choices=[('0', 'เบิกจ้าง'), ('1', 'จัดทำ TOR/ราคากลาง'), ('2', 'รองบประมาณ'), ('3', 'ประกวดราคา'), ('4', 'อื่นๆ')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('vendor_name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อผู้รับจ้าง')),
            ],
        ),
        migrations.CreateModel(
            name='Wbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs', models.CharField(max_length=12, unique=True)),
                ('amt', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('wbs_type', models.CharField(choices=[('0', 'ไม่ระบุ'), ('1', 'ค่าแรง'), ('2', 'ค่าท่อ')], default='0', max_length=2)),
                ('con_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=12, unique=True)),
                ('route_name', models.CharField(max_length=200)),
                ('route_level', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('price_E', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('price_W', models.DecimalField(blank=True, decimal_places=4, max_digits=19)),
                ('route_dma', models.CharField(blank=True, max_length=6)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.vendor'),
        ),
    ]
